<?php
//WIP
declare(strict_types=1);
/** @var Opengento\ImageGenerator\Block\ViewerGlb $block */
$fileGlb = $block->getGlbFileUrl();
?>
<?php if($fileGlb): ?>
    <div x-data="{ open: false }" x-cloak>
        <!-- Trigger button -->
        <button @click="open = true" class="btn btn-primary"><?= $escaper->escapeHtml(__('Show 3D view')) ?></button>
        <!-- Modal -->
        <div x-show="open" class="fixed inset-0 z-50 flex items-center justify-center bg-gray-800 bg-opacity-75" x-cloak>
            <div class="p-4 bg-white rounded shadow-lg">
                <h2 class="mb-4 text-xl font-bold"><?= $escaper->escapeHtml(__('The 3d view')) ?></h2>
                <model-viewer
                    src="<?= $fileGlb ?>" ar
                    ios-src="<?= str_replace('.glb', '.usdz', $fileGlb); ?>"
                    shadow-intensity="1"
                    xr-environnement
                    camera-controls touch-action="pan-y" style="width: 350px; height:350px; display:block;"></model-viewer>
                <button @click="open = false" class="btn btn-secondary">Close</button>
            </div>
        </div>
    </div>
    <script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/4.0.0/model-viewer.min.js"></script>
<?php endif; ?>
